import './globals.css'
import { Permanent_Marker } from 'next/font/google'

const permanent = Permanent_Marker({
  subsets: ['latin'],
  weight: '400'
})

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={permanent.className}>{children}</body>
    </html>
  )
}
